In [1]:
import pandas as pd
import plotly.express as px

KeyboardInterrupt:

In [ ]:
# Convert columns to categorical
def convert_columns_to_categorical(df:pd.DataFrame,columns:list[str])->pd.DataFrame:
    for col in columns:
        df[col]=pd.Categorical(df[col])    # Think of exceptional handling
    
    return df

In [ ]:
# Exploring the Database
def explore_data(df:pd.DataFrame)->None:
    print(f"Samples of the dataset")
    display(df.sample(5))
    print(f"Shape of Data is {df.shape}")
    print(f"List of columns is {df.columns}")
    print(f"Information of the dataset is {df.info()}")
    print(f"Descriptive statistics of real-value columns :")
    display(df.describe())
    print(f" Missing value count is {df.isna().sum()}")

In [ ]:
dtc_code_path=r"F:\KPIT\Pandas_All\Datasets\dtc_codes.csv"
sensor_data_file_path=r"F:\KPIT\Pandas_All\Datasets\ecu_sensor_data.csv"

In [ ]:
sensor_df=pd.read_csv(sensor_data_file_path,index_col="timestamp")
sensor_df=convert_columns_to_categorical(sensor_df,["sensor_type","unit"])
sensor_df.index=pd.to_datetime(sensor_df.index)
dtc_df=pd.read_csv(dtc_code_path,index_col="timestamp")
dtc_df=convert_columns_to_categorical(dtc_df,["severity","dtc_code"])

In [ ]:
explore_data(sensor_df)

Samples of the dataset

                    vehicle_id        sensor_type  value   unit
timestamp
2025-10-01 09:21:58     VEH003      oxygen_sensor   0.97  Volts
2025-10-01 09:17:33     VEH002  throttle_position  39.35      %
2025-10-01 09:43:43     VEH001      oxygen_sensor   1.08  Volts
2025-10-01 12:33:00     VEH001  throttle_position  15.93      %
2025-10-01 11:21:07     VEH002      oxygen_sensor   0.63  Volts

Shape of Data is (20000, 4)
List of columns is Index(['vehicle_id', 'sensor_type', 'value', 'unit'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 20000 entries, 2025-10-01 08:00:00 to 2025-10-01 13:33:19
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vehicle_id   20000 non-null  object
 1   sensor_type  20000 non-null  category
 2   value        20000 non-null  float64
 3   unit         20000 non-null  category
dtypes: category(2), float64(1), object(1)
memory usage: 508.2+ KB
Information of the dataset is None
Descriptive statistics of real-value columns :

              value
count  20000.000000
mean     647.828764
std     1094.448998
min        0.000000
25%        1.040000
50%       61.290000
75%      106.532500
max     4056.460000

 Missing value count is vehicle_id     0
sensor_type    0
value          0
unit           0
dtype: int64

In [ ]:
explore_data(dtc_df)

Samples of the dataset

,vehicle_id,dtc_code,description,severity
timestamp,,,,
2025-10-01 12:02:31,VEH003,P0420,Catalyst System Efficiency Below Threshold,Low
2025-10-01 09:26:13,VEH004,P0128,Coolant Thermostat Malfunction,Low
2025-10-01 11:38:49,VEH002,P0171,System Too Lean,Medium
2025-10-01 11:43:29,VEH003,P0135,O2 Sensor Heater Circuit,Medium
2025-10-01 13:08:46,VEH001,P0135,O2 Sensor Heater Circuit,Medium

Shape of Data is (2025, 4)
List of columns is Index(['vehicle_id', 'dtc_code', 'description', 'severity'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
Index: 2025 entries, 2025-10-01 08:00:00 to 2025-10-01 13:33:18
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vehicle_id   2025 non-null   object
 1   dtc_code     2025 non-null   category
 2   description  2025 non-null   object
 3   severity     2025 non-null   category
dtypes: category(2), object(2)
memory usage: 51.8+ KB
Information of the dataset is None
Descriptive statistics of real-value columns :

       vehicle_id dtc_code               description severity
count        2025     2025                      2025     2025
unique          4        5                         5        3
top        VEH004    P0135  O2 Sensor Heater Circuit      Low
freq          513      430                       430      830

 Missing value count is vehicle_id     0
dtc_code       0
description    0
severity       0
dtype: int64

In [ ]:
sensor_df

                    vehicle_id        sensor_type    value     unit
timestamp
2025-10-01 08:00:00     VEH001         engine_rpm  2748.36      RPM
2025-10-01 08:00:01     VEH003       coolant_temp    83.62  Celsius
2025-10-01 08:00:02     VEH002       coolant_temp    91.48  Celsius
2025-10-01 08:00:03     VEH001         engine_rpm  3261.51      RPM
2025-10-01 08:00:04     VEH004         engine_rpm  2382.92      RPM
...                        ...                ...      ...      ...
2025-10-01 13:33:15     VEH004         engine_rpm  2693.91      RPM
2025-10-01 13:33:16     VEH003         engine_rpm  3188.68      RPM
2025-10-01 13:33:17     VEH002  throttle_position    35.68        %
2025-10-01 13:33:18     VEH001         engine_rpm  3356.76      RPM
2025-10-01 13:33:19     VEH001       coolant_temp    68.80  Celsius

[20000 rows x 4 columns]

In [ ]:
dtc_df

,vehicle_id,dtc_code,description,severity
timestamp,,,,
2025-10-01 08:00:00,VEH004,P0135,O2 Sensor Heater Circuit,Medium
2025-10-01 08:00:02,VEH003,P0128,Coolant Thermostat Malfunction,Low
2025-10-01 08:00:08,VEH004,P0135,O2 Sensor Heater Circuit,Medium
2025-10-01 08:00:14,VEH003,P0171,System Too Lean,Medium
2025-10-01 08:00:16,VEH001,P0301,Cylinder 1 Misfire Detected,High
...,...,...,...,...
2025-10-01 13:32:54,VEH001,P0301,Cylinder 1 Misfire Detected,High
2025-10-01 13:32:56,VEH003,P0301,Cylinder 1 Misfire Detected,High
2025-10-01 13:32:59,VEH003,P0420,Catalyst System Efficiency Below Threshold,Low
2025-10-01 13:33:06,VEH003,P0301,Cylinder 1 Misfire Detected,High
2025-10-01 13:33:18,VEH003,P0128,Coolant Thermostat Malfunction,Low

### What is the proportion of various types of sensors in sensor_df?

In [ ]:
result=sensor_df["sensor_type"].value_counts(normalize=True)*100
display(result)
px.bar(result,color=result.index) # We are doing result.index because value_counts returns series i.e array of numbers , but in series there is no anything like of columns , so we have used index.

sensor_type
oxygen_sensor        25.645
coolant_temp         25.095
engine_rpm           24.650
throttle_position    24.610
Name: proportion, dtype: float64

In [ ]:
px.pie(data_frame=result,names=result.index)

In [ ]:
sensor_df.groupby("sensor_type").size()

C:\Users\Pragyan Prakhar\AppData\Local\Temp\ipykernel_12452\3590222791.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

sensor_type
coolant_temp         5019
engine_rpm           4930
oxygen_sensor        5129
throttle_position    4922
dtype: int64

### Average minimum, maximum values for sensor reading ("value") across each category

In [ ]:
result=sensor_df.groupby("sensor_type")[["value"]].agg(["min","max","mean"])
# print(result.columns) # Multi valued index , that's why we have joined it.
# print(sensor_df.index)
# Converting the Multi-Index into the single one.
result.columns=["_".join(col) for col in result.columns]
# display(result)

mapping={
    "coolant_temp":"Celsius",
    "engine_rpm":"RPM",
    "oxygen_sensor":"Volts",
    "throttle_position":"pct(%)"
}
# px.bar(data_frame=result,barmode="group",facet_col=result.index)
print(result.index)
for grp in result.index:
    # display(px.bar(result,y=grp,color=result.index))
    display(px.bar(result.loc[grp],y=grp,color=result.columns,labels={'index':mapping[grp]}))

CategoricalIndex(['coolant_temp', 'engine_rpm', 'oxygen_sensor',
                  'throttle_position'],
                 categories=['coolant_temp', 'engine_rpm', 'oxygen_sensor', 'throttle_position'], ordered=False, dtype='category', name='sensor_type')

C:\Users\Pragyan Prakhar\AppData\Local\Temp\ipykernel_12452\3531928599.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

### get data in min frequency (aggregate by mean_value)

In [ ]:
sensor_df.index

DatetimeIndex(['2025-10-01 08:00:00', '2025-10-01 08:00:01',
               '2025-10-01 08:00:02', '2025-10-01 08:00:03',
               '2025-10-01 08:00:04', '2025-10-01 08:00:05',
               '2025-10-01 08:00:06', '2025-10-01 08:00:07',
               '2025-10-01 08:00:08', '2025-10-01 08:00:09',
               ...
               '2025-10-01 13:33:10', '2025-10-01 13:33:11',
               '2025-10-01 13:33:12', '2025-10-01 13:33:13',
               '2025-10-01 13:33:14', '2025-10-01 13:33:15',
               '2025-10-01 13:33:16', '2025-10-01 13:33:17',
               '2025-10-01 13:33:18', '2025-10-01 13:33:19'],
              dtype='datetime64[ns]', name='timestamp', length=20000, freq=None)

In [ ]:
sensor_df.resample("1min")[["value"]].mean()

                          value
timestamp
2025-10-01 08:00:00  692.547833
2025-10-01 08:01:00  902.920000
2025-10-01 08:02:00  662.052667
2025-10-01 08:03:00  495.253500
2025-10-01 08:04:00  593.545167
...                         ...
2025-10-01 13:29:00  711.030167
2025-10-01 13:30:00  819.415833
2025-10-01 13:31:00  502.711333
2025-10-01 13:32:00  475.755833
2025-10-01 13:33:00  963.390000

[334 rows x 1 columns]

In [ ]:
result=sensor_df.groupby("sensor_type",observed=True).resample("1min")[["value"]].mean()
result

                                           value
sensor_type       timestamp
coolant_temp      2025-10-01 08:00:00  84.657778
                  2025-10-01 08:01:00  81.377059
                  2025-10-01 08:02:00  83.586111
                  2025-10-01 08:03:00  84.975625
                  2025-10-01 08:04:00  83.243750
...                                          ...
throttle_position 2025-10-01 13:29:00  30.023077
                  2025-10-01 13:30:00  30.301333
                  2025-10-01 13:31:00  24.744545
                  2025-10-01 13:32:00  27.006000
                  2025-10-01 13:33:00  28.032500

[1336 rows x 1 columns]

In [ ]:
result=result.unstack(0)
result.columns=[idx[1]+"_"+idx[0] for idx in result.columns]
result
print(result.columns)

Index(['coolant_temp_value', 'engine_rpm_value', 'oxygen_sensor_value',
       'throttle_position_value'],
      dtype='object')

In [ ]:
for col in result.columns:
    display(px.line(data_frame=result[col],x=result.index,y=result[col],markers=True))

In [ ]:
dtc_df

,vehicle_id,dtc_code,description,severity
timestamp,,,,
2025-10-01 08:00:00,VEH004,P0135,O2 Sensor Heater Circuit,Medium
2025-10-01 08:00:02,VEH003,P0128,Coolant Thermostat Malfunction,Low
2025-10-01 08:00:08,VEH004,P0135,O2 Sensor Heater Circuit,Medium
2025-10-01 08:00:14,VEH003,P0171,System Too Lean,Medium
2025-10-01 08:00:16,VEH001,P0301,Cylinder 1 Misfire Detected,High
...,...,...,...,...
2025-10-01 13:32:54,VEH001,P0301,Cylinder 1 Misfire Detected,High
2025-10-01 13:32:56,VEH003,P0301,Cylinder 1 Misfire Detected,High
2025-10-01 13:32:59,VEH003,P0420,Catalyst System Efficiency Below Threshold,Low
2025-10-01 13:33:06,VEH003,P0301,Cylinder 1 Misfire Detected,High
2025-10-01 13:33:18,VEH003,P0128,Coolant Thermostat Malfunction,Low

### Count of severity categories for each of the dtc code groups

In [ ]:
res=dtc_df.groupby(["dtc_code","severity"])["severity"].size().unstack()
display(res.columns)
res

C:\Users\Pragyan Prakhar\AppData\Local\Temp\ipykernel_12452\1666954120.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

CategoricalIndex(['High', 'Low', 'Medium'], categories=['High', 'Low', 'Medium'], ordered=False, dtype='category', name='severity')

severity  High  Low  Medium
dtc_code
P0128        0  401       0
P0135        0    0     430
P0171        0    0     391
P0301      374    0       0
P0420        0  429       0

In [ ]:
# One more way
result=dtc_df.groupby("dtc_code",observed=True)[["severity"]].value_counts()
result=pd.DataFrame(result).unstack()
result.columns=[idx[1]+"_"+idx[0] for idx in result.columns]
result

          High_count  Low_count  Medium_count
dtc_code
P0128              0        401             0
P0135              0          0           430
P0171              0          0           391
P0301            374          0             0
P0420              0        429             0

### Join Dataframes based on timestamps

In [ ]:
sensor_df.merge(dtc_df,left_on="vehicle_id",right_on="vehicle_id",how="outer")

,vehicle_id,sensor_type,value,unit,dtc_code,description,severity
0,VEH001,engine_rpm,2748.36,RPM,P0301,Cylinder 1 Misfire Detected,High
1,VEH001,engine_rpm,2748.36,RPM,P0301,Cylinder 1 Misfire Detected,High
2,VEH001,engine_rpm,2748.36,RPM,P0301,Cylinder 1 Misfire Detected,High
3,VEH001,engine_rpm,2748.36,RPM,P0128,Coolant Thermostat Malfunction,Low
4,VEH001,engine_rpm,2748.36,RPM,P0128,Coolant Thermostat Malfunction,Low
...,...,...,...,...,...,...,...
10126756,VEH004,engine_rpm,2693.91,RPM,P0128,Coolant Thermostat Malfunction,Low
10126757,VEH004,engine_rpm,2693.91,RPM,P0301,Cylinder 1 Misfire Detected,High
10126758,VEH004,engine_rpm,2693.91,RPM,P0301,Cylinder 1 Misfire Detected,High
10126759,VEH004,engine_rpm,2693.91,RPM,P0420,Catalyst System Efficiency Below Threshold,Low
10126760,VEH004,engine_rpm,2693.91,RPM,P0128,Coolant Thermostat Malfunction,Low

In [ ]:
# The above data contains duplicates
# We use drop duplicates to drop the duplicate rows
merged_df=sensor_df.merge(dtc_df,left_on="vehicle_id",right_on="vehicle_id",how="outer").drop_duplicates()

### Grouped the merged data based on the vehicle ID. Expor the grouped data as a separate sheet in an excel file.

In [ ]:
grouped_df=merged_df.groupby("vehicle_id")
grouped_df

In [ ]:
merged_df

,vehicle_id,sensor_type,value,unit,dtc_code,description,severity
0,VEH001,engine_rpm,2748.36,RPM,P0301,Cylinder 1 Misfire Detected,High
3,VEH001,engine_rpm,2748.36,RPM,P0128,Coolant Thermostat Malfunction,Low
5,VEH001,engine_rpm,2748.36,RPM,P0420,Catalyst System Efficiency Below Threshold,Low
6,VEH001,engine_rpm,2748.36,RPM,P0171,System Too Lean,Medium
12,VEH001,engine_rpm,2748.36,RPM,P0135,O2 Sensor Heater Circuit,Medium
...,...,...,...,...,...,...,...
10126248,VEH004,engine_rpm,2693.91,RPM,P0135,O2 Sensor Heater Circuit,Medium
10126250,VEH004,engine_rpm,2693.91,RPM,P0301,Cylinder 1 Misfire Detected,High
10126251,VEH004,engine_rpm,2693.91,RPM,P0171,System Too Lean,Medium
10126259,VEH004,engine_rpm,2693.91,RPM,P0128,Coolant Thermostat Malfunction,Low
10126264,VEH004,engine_rpm,2693.91,RPM,P0420,Catalyst System Efficiency Below Threshold,Low

In [ ]:
grouped_df.groups

{'VEH001': [0, 3, 5, 6, 12, 510, 513, 515, 516, 522, 1020, 1023, 1025, 1026, 1032, 1530, 1533, 1535, 1536, 1542, 2040, 2043, 2045, 2046, 2052, 2550, 2553, 2555, 2556, 2562, 3060, 3063, 3065, 3066, 3072, 3570, 3573, 3575, 3576, 3582, 4080, 4083, 4085, 4086, 4092, 4590, 4593, 4595, 4596, 4602, 5100, 5103, 5105, 5106, 5112, 5610, 5613, 5615, 5616, 5622, 6120, 6123, 6125, 6126, 6132, 6630, 6633, 6635, 6636, 6642, 7140, 7143, 7145, 7146, 7152, 7650, 7653, 7655, 7656, 7662, 8160, 8163, 8165, 8166, 8172, 8670, 8673, 8675, 8676, 8682, 9180, 9183, 9185, 9186, 9192, 9690, 9693, 9695, 9696, 9702, ...], 'VEH002': [2569890, 2569891, 2569894, 2569895, 2569899, 2570384, 2570385, 2570388, 2570389, 2570393, 2570878, 2570879, 2570882, 2570883, 2570887, 2571372, 2571373, 2571376, 2571377, 2571381, 2571866, 2571867, 2571870, 2571871, 2571875, 2572360, 2572361, 2572364, 2572365, 2572369, 2572854, 2572855, 2572858, 2572859, 2572863, 2573348, 2573349, 2573352, 2573353, 2573357, 2573842, 2573843, 2573846, 2573847, 2573851, 2574336, 2574337, 2574340, 2574341, 2574345, 2574830, 2574831, 2574834, 2574835, 2574839, 2575324, 2575325, 2575328, 2575329, 2575333, 2575818, 2575819, 2575822, 2575823, 2575827, 2576312, 2576313, 2576316, 2576317, 2576321, 2576806, 2576807, 2576810, 2576811, 2576815, 2577300, 2577301, 2577304, 2577305, 2577309, 2577794, 2577795, 2577798, 2577799, 2577803, 2578288, 2578289, 2578292, 2578293, 2578297, 2579276, 2579277, 2579280, 2579281, 2579285, 2579770, 2579771, 2579774, 2579775, 2579779, ...], 'VEH003': [4996912, 4996913, 4996914, 4996915, 4996919, 4997420, 4997421, 4997422, 4997423, 4997427, 4997928, 4997929, 4997930, 4997931, 4997935, 4998436, 4998437, 4998438, 4998439, 4998443, 4998944, 4998945, 4998946, 4998947, 4998951, 4999452, 4999453, 4999454, 4999455, 4999459, 4999960, 4999961, 4999962, 4999963, 4999967, 5000468, 5000469, 5000470, 5000471, 5000475, 5000976, 5000977, 5000978, 5000979, 5000983, 5001484, 5001485, 5001486, 5001487, 5001491, 5001992, 5001993, 5001994, 5001995, 5001999, 5002500, 5002501, 5002502, 5002503, 5002507, 5003008, 5003009, 5003010, 5003011, 5003015, 5003516, 5003517, 5003518, 5003519, 5003523, 5004024, 5004025, 5004026, 5004027, 5004031, 5004532, 5004533, 5004534, 5004535, 5004539, 5005040, 5005041, 5005042, 5005043, 5005047, 5005548, 5005549, 5005550, 5005551, 5005555, 5006056, 5006057, 5006058, 5006059, 5006063, 5006564, 5006565, 5006566, 5006567, 5006571, ...], 'VEH004': [7514052, 7514054, 7514055, 7514063, 7514068, 7514565, 7514567, 7514568, 7514576, 7514581, 7515078, 7515080, 7515081, 7515089, 7515094, 7515591, 7515593, 7515594, 7515602, 7515607, 7516104, 7516106, 7516107, 7516115, 7516120, 7516617, 7516619, 7516620, 7516628, 7516633, 7517130, 7517132, 7517133, 7517141, 7517146, 7517643, 7517645, 7517646, 7517654, 7517659, 7518156, 7518158, 7518159, 7518167, 7518172, 7518669, 7518671, 7518672, 7518680, 7518685, 7519182, 7519184, 7519185, 7519193, 7519198, 7519695, 7519697, 7519698, 7519706, 7519711, 7520208, 7520210, 7520211, 7520219, 7520224, 7520721, 7520723, 7520724, 7520732, 7520737, 7521234, 7521236, 7521237, 7521245, 7521250, 7521747, 7521749, 7521750, 7521758, 7521763, 7522260, 7522262, 7522263, 7522271, 7522276, 7522773, 7522775, 7522776, 7522784, 7522789, 7523286, 7523288, 7523289, 7523297, 7523302, 7523799, 7523801, 7523802, 7523810, 7523815, ...]}

In [ ]:
# grouped_df.groups
for ke in grouped_df.groups:
    print(ke)

VEH001
VEH002
VEH003
VEH004

In [ ]:
excel_path=r"dummy_output.xlsx"
with pd.ExcelWriter(excel_path) as excel_file:
    for grp in grouped_df.groups.keys():
        grouped_df.get_group(grp).to_excel(excel_file,sheet_name=grp)

### How to load the dataset from excel sheet into different dataframes or as a single dataframe

In [ ]:
excel_path=r"dummy_output.xlsx"
dataframe_list:list[pd.DataFrame]=[]
for grp in grouped_df.groups:
    dataframe_list.append(pd.read_excel(excel_path,sheet_name=grp))

print(dataframe_list)

[       Unnamed: 0 vehicle_id   sensor_type    value     unit dtc_code  \
0               0     VEH001    engine_rpm  2748.36      RPM    P0301
1               3     VEH001    engine_rpm  2748.36      RPM    P0128
2               5     VEH001    engine_rpm  2748.36      RPM    P0420
3               6     VEH001    engine_rpm  2748.36      RPM    P0171
4              12     VEH001    engine_rpm  2748.36      RPM    P0135
...           ...        ...           ...      ...      ...      ...
17750     2569380     VEH001  coolant_temp    68.80  Celsius    P0301
17751     2569383     VEH001  coolant_temp    68.80  Celsius    P0128
17752     2569385     VEH001  coolant_temp    68.80  Celsius    P0420
17753     2569386     VEH001  coolant_temp    68.80  Celsius    P0171
17754     2569392     VEH001  coolant_temp    68.80  Celsius    P0135

                                      description severity
0                     Cylinder 1 Misfire Detected     High
1                  Coolant Thermostat Malfunction      Low
2      Catalyst System Efficiency Below Threshold      Low
3                                 System Too Lean   Medium
4                        O2 Sensor Heater Circuit   Medium
...                                           ...      ...
17750                 Cylinder 1 Misfire Detected     High
17751              Coolant Thermostat Malfunction      Low
17752  Catalyst System Efficiency Below Threshold      Low
17753                             System Too Lean   Medium
17754                    O2 Sensor Heater Circuit   Medium

[17755 rows x 8 columns],        Unnamed: 0 vehicle_id        sensor_type  value     unit dtc_code  \
0         2569890     VEH002       coolant_temp  91.48  Celsius    P0171
1         2569891     VEH002       coolant_temp  91.48  Celsius    P0420
2         2569894     VEH002       coolant_temp  91.48  Celsius    P0301
3         2569895     VEH002       coolant_temp  91.48  Celsius    P0128
4         2569899     VEH002       coolant_temp  91.48  Celsius    P0135
...           ...        ...                ...    ...      ...      ...
17090     4996418     VEH002  throttle_position  35.68        %    P0171
17091     4996419     VEH002  throttle_position  35.68        %    P0420
17092     4996422     VEH002  throttle_position  35.68        %    P0301
17093     4996423     VEH002  throttle_position  35.68        %    P0128
17094     4996427     VEH002  throttle_position  35.68        %    P0135

                                      description severity
0                                 System Too Lean   Medium
1      Catalyst System Efficiency Below Threshold      Low
2                     Cylinder 1 Misfire Detected     High
3                  Coolant Thermostat Malfunction      Low
4                        O2 Sensor Heater Circuit   Medium
...                                           ...      ...
17090                             System Too Lean   Medium
17091  Catalyst System Efficiency Below Threshold      Low
17092                 Cylinder 1 Misfire Detected     High
17093              Coolant Thermostat Malfunction      Low
17094                    O2 Sensor Heater Circuit   Medium

[17095 rows x 8 columns],        Unnamed: 0 vehicle_id   sensor_type    value     unit dtc_code  \
0         4996912     VEH003  coolant_temp    83.62  Celsius    P0128
1         4996913     VEH003  coolant_temp    83.62  Celsius    P0171
2         4996914     VEH003  coolant_temp    83.62  Celsius    P0420
3         4996915     VEH003  coolant_temp    83.62  Celsius    P0135
4         4996919     VEH003  coolant_temp    83.62  Celsius    P0301
...           ...        ...           ...      ...      ...      ...
16945     7513544     VEH003    engine_rpm  3188.68      RPM    P0128
16946     7513545     VEH003    engine_rpm  3188.68      RPM    P0171
16947     7513546     VEH003    engine_rpm  3188.68      RPM    P0420
16948     7513547     VEH003    engine_rpm  3188.68      RPM    P0135
16949     7513551     VEH003    engine_rpm  3188.68      RPM    P0301

                                      description severity
0                  Coolant Thermostat Malfunction      Low
1                                 System Too Lean   Medium
2      Catalyst System Efficiency Below Threshold      Low
3                        O2 Sensor Heater Circuit   Medium
4                     Cylinder 1 Misfire Detected     High
...                                           ...      ...
16945              Coolant Thermostat Malfunction      Low
16946                             System Too Lean   Medium
16947  Catalyst System Efficiency Below Threshold      Low
16948                    O2 Sensor Heater Circuit   Medium
16949                 Cylinder 1 Misfire Detected     High

[16950 rows x 8 columns],        Unnamed: 0 vehicle_id sensor_type    value unit dtc_code  \
0         7514052     VEH004  engine_rpm  2382.92  RPM    P0135
1         7514054     VEH004  engine_rpm  2382.92  RPM    P0301
2         7514055     VEH004  engine_rpm  2382.92  RPM    P0171
3         7514063     VEH004  engine_rpm  2382.92  RPM    P0128
4         7514068     VEH004  engine_rpm  2382.92  RPM    P0420
...           ...        ...         ...      ...  ...      ...
17515    10126248     VEH004  engine_rpm  2693.91  RPM    P0135
17516    10126250     VEH004  engine_rpm  2693.91  RPM    P0301
17517    10126251     VEH004  engine_rpm  2693.91  RPM    P0171
17518    10126259     VEH004  engine_rpm  2693.91  RPM    P0128
17519    10126264     VEH004  engine_rpm  2693.91  RPM    P0420

                                      description severity
0                        O2 Sensor Heater Circuit   Medium
1                     Cylinder 1 Misfire Detected     High
2                                 System Too Lean   Medium
3                  Coolant Thermostat Malfunction      Low
4      Catalyst System Efficiency Below Threshold      Low
...                                           ...      ...
17515                    O2 Sensor Heater Circuit   Medium
17516                 Cylinder 1 Misfire Detected     High
17517                             System Too Lean   Medium
17518              Coolant Thermostat Malfunction      Low
17519  Catalyst System Efficiency Below Threshold      Low

[17520 rows x 8 columns]]

In [ ]:
dataframe_list[0]

,Unnamed: 0,vehicle_id,sensor_type,value,unit,dtc_code,description,severity
0,0,VEH001,engine_rpm,2748.36,RPM,P0301,Cylinder 1 Misfire Detected,High
1,3,VEH001,engine_rpm,2748.36,RPM,P0128,Coolant Thermostat Malfunction,Low
2,5,VEH001,engine_rpm,2748.36,RPM,P0420,Catalyst System Efficiency Below Threshold,Low
3,6,VEH001,engine_rpm,2748.36,RPM,P0171,System Too Lean,Medium
4,12,VEH001,engine_rpm,2748.36,RPM,P0135,O2 Sensor Heater Circuit,Medium
...,...,...,...,...,...,...,...,...
17750,2569380,VEH001,coolant_temp,68.80,Celsius,P0301,Cylinder 1 Misfire Detected,High
17751,2569383,VEH001,coolant_temp,68.80,Celsius,P0128,Coolant Thermostat Malfunction,Low
17752,2569385,VEH001,coolant_temp,68.80,Celsius,P0420,Catalyst System Efficiency Below Threshold,Low
17753,2569386,VEH001,coolant_temp,68.80,Celsius,P0171,System Too Lean,Medium
17754,2569392,VEH001,coolant_temp,68.80,Celsius,P0135,O2 Sensor Heater Circuit,Medium

## Alternate Option

In [ ]:
schema={"Unnamed: 0" : [] , "vehicle_id":[], "sensor_type":[] , "value":[] , "unit":[], "dtc_code":[] , "description":[], "severity":[]}
result_df=pd.DataFrame(schema)
result_df

Empty DataFrame
Columns: [Unnamed: 0, vehicle_id, sensor_type, value, unit, dtc_code, description, severity]
Index: []

In [ ]:
for grp in grouped_df.groups:
    result_df=pd.concat([result_df,pd.read_excel(excel_path , sheet_name=grp)])

In [ ]:
print(result_df)

       Unnamed: 0 vehicle_id sensor_type    value unit dtc_code  \
0             0.0     VEH001  engine_rpm  2748.36  RPM    P0301
1             3.0     VEH001  engine_rpm  2748.36  RPM    P0128
2             5.0     VEH001  engine_rpm  2748.36  RPM    P0420
3             6.0     VEH001  engine_rpm  2748.36  RPM    P0171
4            12.0     VEH001  engine_rpm  2748.36  RPM    P0135
...           ...        ...         ...      ...  ...      ...
17515  10126248.0     VEH004  engine_rpm  2693.91  RPM    P0135
17516  10126250.0     VEH004  engine_rpm  2693.91  RPM    P0301
17517  10126251.0     VEH004  engine_rpm  2693.91  RPM    P0171
17518  10126259.0     VEH004  engine_rpm  2693.91  RPM    P0128
17519  10126264.0     VEH004  engine_rpm  2693.91  RPM    P0420

                                      description severity
0                     Cylinder 1 Misfire Detected     High
1                  Coolant Thermostat Malfunction      Low
2      Catalyst System Efficiency Below Threshold      Low
3                                 System Too Lean   Medium
4                        O2 Sensor Heater Circuit   Medium
...                                           ...      ...
17515                    O2 Sensor Heater Circuit   Medium
17516                 Cylinder 1 Misfire Detected     High
17517                             System Too Lean   Medium
17518              Coolant Thermostat Malfunction      Low
17519  Catalyst System Efficiency Below Threshold      Low

[69320 rows x 8 columns]

In [ ]:
temp_df=sensor_df.groupby("sensor_type",observed=False)[["sensor_type","unit"]].agg(["count"])

In [ ]:
temp_df.stack()

C:\Users\Pragyan Prakhar\AppData\Local\Temp\ipykernel_12452\1362379900.py:1: FutureWarning:

The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.

                         sensor_type  unit
sensor_type
coolant_temp      count         5019  5019
engine_rpm        count         4930  4930
oxygen_sensor     count         5129  5129
throttle_position count         4922  4922

In [ ]:
sensor_df.pivot_table(index="sensor_type",columns="unit",values="value",aggfunc=["min","max"],observed=True)

                   min                         max
unit                 % Celsius    RPM Volts      % Celsius      RPM Volts
sensor_type
coolant_temp       NaN    60.0    NaN   NaN    NaN   110.0      NaN   NaN
engine_rpm         NaN     NaN  800.0   NaN    NaN     NaN  4056.46   NaN
oxygen_sensor      NaN     NaN    NaN   0.1    NaN     NaN      NaN   1.2
throttle_position  0.0     NaN    NaN   NaN  81.43     NaN      NaN   NaN

### Melting increases the number of rows in the table 
-> All data for metling has to come from one of the columns, no index

In [ ]:
temp_df=sensor_df.reset_index()
temp_df.melt(id_vars="timestamp",value_vars=["vehicle_id","sensor_type"],value_name="Attribute")
# id_vars is identification variable and that should be index
# value_vars is the name of the cols which is needed to be clubbed.
# value_name is the name of the column

                timestamp     variable          Attribute
0     2025-10-01 08:00:00   vehicle_id             VEH001
1     2025-10-01 08:00:01   vehicle_id             VEH003
2     2025-10-01 08:00:02   vehicle_id             VEH002
3     2025-10-01 08:00:03   vehicle_id             VEH001
4     2025-10-01 08:00:04   vehicle_id             VEH004
...                   ...          ...                ...
39995 2025-10-01 13:33:15  sensor_type         engine_rpm
39996 2025-10-01 13:33:16  sensor_type         engine_rpm
39997 2025-10-01 13:33:17  sensor_type  throttle_position
39998 2025-10-01 13:33:18  sensor_type         engine_rpm
39999 2025-10-01 13:33:19  sensor_type       coolant_temp

[40000 rows x 3 columns]