In [2]:
import pandas as pd
import plotly.express as px
# Loading the dataset
car_data_sales_file_path=r"F:\KPIT\Pandas_All\Datasets\car_sales_usa_data 1.csv"
df=pd.read_csv(car_data_sales_file_path,parse_dates=["Sale Date"])
df

,Year,Make,Model,Trim,Body,Transmission,Vehicle Identification Number,Odometer,Seller,Market Price,Selling Price,Sale Date,State
0,2004,Ford,Explorer,Limited,SUV,Automatic,1fmzu65k54ua59709,171116,Barnett Finance Company,2500,1700,2015-02-17,Georgia
1,2013,Chevrolet,Impala,LS Fleet,sedan,Automatic,2g1wf5e3xd1160771,57634,The Hertz Corporation,8925,8900,2015-06-16,California
2,2014,Dodge,Grand Caravan,SXT,Minivan,Automatic,2c4rdgcg2er173190,37928,Avis Corporation,16200,16200,2015-02-12,South Carolina
3,2007,Ford,F-150,XLT,supercab,Automatic,1ftpx14557fa02257,108246,Tdaf Remarketing,10300,11000,2015-06-16,Florida
4,2011,Hyundai,Elantra,GLS PZEV,Sedan,Automatic,5npdh4aexbh018071,69185,Wholesale Inc # 2,9575,10300,2015-01-21,Tennessee
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2013,Nissan,Altima,2.5,Sedan,Automatic,1n4al3ap5dn468314,32702,Nissan-Infiniti Lt,13800,13000,2015-02-26,Illinois
49996,2005,Mercedes-Benz,E-Class,E320,Sedan,Automatic,wdbuf65j95a624447,123165,Westlake Financial Services,6075,4100,2015-01-08,Florida
49997,2013,Dodge,Dart,SXT,Sedan,Automatic,1c3cdfba9dd143722,47130,Wells Fargo Dealer Services,11400,11000,2015-03-04,Texas
49998,2008,Toyota,RAV4,Limited,SUV,Automatic,jtmzd31vx85115663,102712,Infinity Auto Sales Llc,9525,8600,2015-03-05,Virginia
49999,2013,Chevrolet,Camaro,SS,Convertible,Automatic,2g1fk3dj8d9138852,53105,Tdaf Remarketing,21400,23400,2015-02-17,Florida

### How many records are there per model Year?

In [3]:
df.index

RangeIndex(start=0, stop=50000, step=1)

In [4]:
result_df = df.groupby("Year").size()
result_dff=pd.DataFrame(result_df)
result_dff.rename(columns={0:"Count"},inplace=True)
result_dff.index
px.bar(result_dff,x=result_dff.index,y="Count",title="Number of records per year")

### What is the distribution of vehicle age at sale (Age = Sale Year − Model Year)? Provide basic statistics (count, mean, median, std, min, 25 %, 50 %,75 %, max).

In [5]:
result_dff=df
result_dff["Age"]=df["Sale Date"].dt.year - df["Year"]
result_dff["Age"].describe()
fig = px.histogram(result_dff, x="Age",nbins=20,title="Distribution of Vehicle Age",labels={"Age":"Vehicle Age (Years)"},marginal="box")         # optional: adds a boxplot on top
fig.show()

### Which Body styles are most common? List the top‑5 body styles with their frequencies.

In [6]:
df.columns

Index(['Year', 'Make', 'Model', 'Trim', 'Body', 'Transmission',
       'Vehicle Identification Number', 'Odometer', 'Seller', 'Market Price',
       'Selling Price', 'Sale Date', 'State', 'Age'],
      dtype='object')

In [41]:
# final_df = (
#     df.groupby("Body")
#       .size()
#       .reset_index(name="count")
#       .sort_values("count", ascending=False)
#       .head(5)
#       .reset_index(drop=True)
#         # 🔑 this removes the old index
# )

# final_df
final_df=df.groupby("Body").size()
final_df.reset_index().rename(columns={0:"Count"}).sort_values("Count",ascending=False).head(5).reset_index().drop("index",axis=1)

# px.pie(final_df,names="Body",values="count",title="Top 5 Vehicle Body Style")

        Body  Count
0      Sedan  18515
1        SUV  10466
2      sedan   3972
3        suv   2219
4  Hatchback   2054

In [8]:
df["Body"].value_counts().head(5)

Body
Sedan        18515
SUV          10466
sedan         3972
suv           2219
Hatchback     2054
Name: count, dtype: int64

### What are the minimum, maximum, and average odometer readings across the whole dataset?

In [9]:
# res_df=df.groupby("Odometer").agg()
df["Odometer"].agg(["min","max","mean"])

min          1.00000
max     999999.00000
mean     66914.30302
Name: Odometer, dtype: float64

### How many unique sellers exist in each State?

In [10]:
df.groupby(["State"])["Seller"].nunique()

State
Arizona           159
California        800
Colorado          121
Florida           824
Georgia           410
Hawaii             44
Illinois          174
Indiana            84
Louisiana          38
Maryland          145
Massachusetts     106
Michigan          132
Minnesota         169
Mississippi        48
Missouri          266
Nebraska          101
Nevada            255
New Jersey        299
New Mexico         11
New York           89
North Carolina    317
Ohio              222
Oklahoma            4
Oregon             44
Pennsylvania      489
Puerto Rico        34
South Carolina     92
Tennessee         195
Texas             515
Utah               48
Virginia          190
Washington        134
Wisconsin         171
Name: Seller, dtype: int64

### Show all rows where Selling Price > Market Price

In [11]:
df[df['Selling Price'] > df['Market Price']]

,Year,Make,Model,Trim,Body,Transmission,Vehicle Identification Number,Odometer,Seller,Market Price,Selling Price,Sale Date,State,Age
3,2007,Ford,F-150,XLT,supercab,Automatic,1ftpx14557fa02257,108246,Tdaf Remarketing,10300,11000,2015-06-16,Florida,8
4,2011,Hyundai,Elantra,GLS PZEV,Sedan,Automatic,5npdh4aexbh018071,69185,Wholesale Inc # 2,9575,10300,2015-01-21,Tennessee,4
5,2012,Nissan,Leaf,SL,Hatchback,Automatic,jn1az0cp2ct018461,23801,Nissan Motor Acceptance Corporation,10600,11100,2015-02-25,California,3
6,2010,Dodge,Avenger,SXT,Sedan,Automatic,1b3cc4fb2an189535,110704,Exeter Finance Corp,5100,5600,2015-02-10,Tennessee,5
9,2012,Honda,Accord,LX,Sedan,Automatic,1hgcp2f36ca167629,35478,Ahfc/Honda Lease Trust/Hvt Inc. Eot,11850,12300,2015-05-22,Nevada,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49981,2014,Chevrolet,Cruze,1LT,Sedan,Automatic,1g1pc5sbxe7180760,38916,Avis Corporation,11600,12500,2015-03-03,Texas,1
49987,2012,Infiniti,M,M37x,sedan,Automatic,jn1by1ar8cm393945,52454,Nissan Infiniti Lt,22000,22400,2015-06-18,Illinois,3
49991,2013,Lexus,GS 350,Base,sedan,Automatic,jthbe1bl2d5014108,26897,High Bid Trading Co Inc,30500,31500,2015-06-18,California,2
49992,2012,Lexus,ES 350,Base,Sedan,Automatic,jthbk1egxc2492283,30255,Lexus Financial Services,21900,24750,2015-02-04,California,3
49999,2013,Chevrolet,Camaro,SS,Convertible,Automatic,2g1fk3dj8d9138852,53105,Tdaf Remarketing,21400,23400,2015-02-17,Florida,2

### Retrieve automatic‑transmission vehicles in California with Odometer < 30 000 miles.

In [12]:
df.loc[(df["Transmission"]=="Automatic") & (df["State"]=="California") & ((df["Odometer"] < 30000))]

,Year,Make,Model,Trim,Body,Transmission,Vehicle Identification Number,Odometer,Seller,Market Price,Selling Price,Sale Date,State,Age
5,2012,Nissan,Leaf,SL,Hatchback,Automatic,jn1az0cp2ct018461,23801,Nissan Motor Acceptance Corporation,10600,11100,2015-02-25,California,3
33,2011,BMW,3 Series,328i,Sedan,Automatic,wbaph5c54bf093310,29639,Financial Services Remarketing (Lease),19050,17900,2015-02-12,California,4
35,2013,Honda,Civic,LX,Sedan,Automatic,19xfb2f53de240787,14379,Ahfc/Honda Lease Trust/Hvt Inc.,13650,14900,2015-01-29,California,2
44,2015,Nissan,Altima,2.5 S,Sedan,Automatic,1n4al3ap2fn315814,18181,Enterprise Veh Exchange/Rental,16050,16600,2015-02-19,California,0
66,2014,Jeep,Compass,Sport,SUV,Automatic,1c4njcba5ed817877,19984,Hertz Corporation/Gdp,14050,13900,2015-06-03,California,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49943,2014,Dodge,Grand Caravan,SXT,Minivan,Automatic,2c4rdgcg6er430304,13482,Enterprise Vehicle Exchange / Tra / Rental / T...,17150,12300,2015-01-22,California,1
49953,2014,Ford,Focus,SE,Sedan,Automatic,1fadp3f25el242155,17734,Ford Motor Credit Company,12600,12600,2015-01-29,California,1
49968,2010,Jeep,Wrangler,Sport,SUV,Automatic,1j4aa2d18al146575,15745,Aaero Sweet Company,19100,22000,2015-02-26,California,5
49984,2014,Mercedes-Benz,CLA-Class,CLA250,Sedan,Automatic,wddsj4eb2en035064,6017,Mercedes-Benz Usa,29700,24750,2014-12-18,California,0
49991,2013,Lexus,GS 350,Base,sedan,Automatic,jthbe1bl2d5014108,26897,High Bid Trading Co Inc,30500,31500,2015-06-18,California,2

### For each Make, keep the record with the most recent Sale Date

In [13]:
ress=df.loc[df.groupby("Make")["Sale Date"].idxmax()]
ress

,Year,Make,Model,Trim,Body,Transmission,Vehicle Identification Number,Odometer,Seller,Market Price,Selling Price,Sale Date,State,Age
34661,2005,Acura,RSX,Base,hatchback,Automatic,jh4dc54825s004888,143669,Ed Napleton Acura,3525,1900,2015-07-08,Wisconsin,10
5806,2008,Aston Martin,V8 Vantage,N400 Roadster,convertible,Automatic,scfbf04b08gd08294,13479,Performance Auto Sales Llc,55200,57000,2015-06-17,Florida,7
19405,2010,Audi,A4,2.0T Premium quattro,Sedan,Manual,waudfafl8an047964,80318,Rob Lambdin'S University Dodge,12400,12200,2015-07-03,Florida,5
4891,2012,BMW,3 Series,328i,Sedan,Automatic,wba3a5c54cf347733,35587,Lauderdale Imports Ltd Bmw Pembrok Pines,21600,23200,2015-07-07,Florida,3
45450,2005,Bentley,Continental GT,Base,Coupe,Automatic,scbcr63w15c025701,42409,Payless Auto Sales Inc,48600,54000,2015-07-02,California,10
17292,2011,Buick,LaCrosse,CXL,Sedan,Automatic,1g4gc5edxbf133777,83050,Gm Financial,11950,13003,2015-07-03,Texas,4
36145,2013,Cadillac,XTS,Platinum,sedan,Automatic,2g61u5s34d9198920,33603,Wells Fargo Dealer Services,31300,31800,2015-07-02,Texas,2
17943,2013,Chevrolet,Impala,LTZ,Sedan,Automatic,2g1wc5e39d1214070,60025,The Hertz Corporation,10100,10300,2015-07-08,California,2
2031,2013,Chrysler,200,LX,Sedan,Automatic,1c3ccbab2dn734510,45108,Enterprise Veh Exchange/Rental,9500,10900,2015-07-09,California,2
4576,2014,Dodge,Challenger,SXT,Coupe,Automatic,2c3cdyagxeh233855,26802,Enterprise Veh Exchange/Rental,18200,18900,2015-07-08,California,1
21507,2013,FIAT,500,Sport,Hatchback,Automatic,3c3cffbr0dt618555,47634,The Hertz Corporation,8475,8900,2015-06-18,Illinois,2
49965,2012,Fisker,Karma,Eco-Sport,Sedan,Automatic,yh4k14aa4ca000463,18593,Innovative Auto Llc,48200,46500,2015-02-12,Georgia,3
2783,2015,Ford,Fusion,SE,Sedan,Automatic,3fa6p0h71fr189618,10,Ford Motor Credit Company,33900,42100,2015-07-09,Tennessee,0
36634,2014,GMC,Savana Cargo,2500,Van,Automatic,1gtw7fca7e1904930,13849,U-Haul,18950,19800,2015-06-24,Tennessee,1
18209,1995,Geo,Prizm,Base,Sedan,Automatic,1y1sk5266sz002895,162909,Purple Heart Services Inc,500,550,2015-05-28,New Jersey,20
18955,2006,HUMMER,H3,Base,suv,Automatic,5gtdn136368101660,91398,Multi Auto Trading Inc,11400,10000,2015-07-09,Michigan,9
9397,2010,Honda,Civic,LX,coupe,Automatic,2hgfg1b69ah503277,70554,M & M Cars Trucks Vans Inc,7125,7600,2015-07-07,California,5
13801,2015,Hyundai,Genesis,3.8,Sedan,Automatic,kmhgn4je0fu039752,3866,Hyundai Motor Finance,35300,34000,2015-07-03,Florida,0
31701,2012,Infiniti,G Coupe,G37x,G Coupe,Automatic,jn1cv6el0cm470372,54680,Nissan Infiniti Lt,19400,17200,2015-07-09,Tennessee,3
20521,1999,Isuzu,Rodeo,S,suv,Automatic,4s2ck58w3x4355717,122039,Park Cities Volkswagen,925,1100,2015-06-11,Texas,16
928,2011,Jaguar,XK,Base,coupe,Automatic,sajwa4fb6blb40731,26922,Luxury Motor Car Company,37700,39500,2015-06-18,Ohio,4
1561,2008,Jeep,Patriot,Sport,suv,Automatic,1j8ff28w48d784872,85290,Select Lane,6450,7300,2015-07-09,Minnesota,7
21115,2012,Kia,Optima,LX,Sedan,Automatic,5xxgm4a70cg062555,75262,Kia Motors Finance,9650,8500,2015-07-08,Minnesota,3
31995,2007,Lamborghini,Gallardo,Spyder,Convertible,Automatic,zhwgu22t97la05738,18624,Richard J Bartlett Jr Enterprises,111000,110000,2015-05-21,California,8
4373,2012,Land Rover,Range Rover Evoque,Pure,suv,Automatic,salvr2bg3ch685496,21570,Okemos Auto Collection,34600,32000,2015-06-18,Michigan,3
35884,2008,Lexus,LS 460,Base,sedan,Automatic,jthbl46f185052818,110153,Plaza Motor Company,17350,15000,2015-07-07,Missouri,7
17457,2013,Lincoln,MKX,Base,SUV,Automatic,2lmdj8jk8dbl18076,20759,Ford Motor Credit Company Llc,28500,27300,2015-07-08,Michigan,2
17172,2012,MINI,Cooper,Base,hatchback,Manual,wmwsu3c53ct186235,31904,Bmw Mini Financial Services,11250,10600,2015-06-19,Nevada,3
8067,2006,Maserati,Quattroporte,Base,sedan,Automatic,zamce39a260023277,62538,E Motor Cars,18500,18000,2015-06-18,California,9
49037,2008,Mazda,B-Series Truck,B4000,Cab Plus 4,Manual,4f4zr47e88pm00663,38364,Automobiles Paille Inc,11300,12500,2015-06-30,Michigan,7
28531,2009,Mercedes-Benz,C-Class,C350 Sport,Sedan,Automatic,wddgf56x19f215580,96147,Meridian Remarketing,12450,12700,2015-07-08,Texas,6
2090,2001,Mercury,Sable,LS Premium,sedan,Automatic,1mefm55s11a648656,125741,Brandon Mitsubishi,675,500,2015-06-18,Florida,14
49952,2010,Mitsubishi,Outlander,ES,SUV,Automatic,ja4as2aw4az014522,69079,Reliable Financial Services Inc,6550,8300,2015-07-02,Puerto Rico,5
47112,2014,Nissan,Maxima,3.5 S,Sedan,Automatic,1n4aa5ap1ec457602,32231,Avis Corporation,15500,16800,2015-07-09,Texas,1
19937,2002,Oldsmobile,Alero,GX,sedan,Automatic,1g3nk52f12c223423,108862,Darcars Toyota Of Frederick,950,550,2015-06-16,Maryland,13
5510,1998,Plymouth,Neon,Style,Sedan,Automatic,3p3es47c6wt258638,103110,Dt Credit Corporation,700,400,2015-05-28,California,17
35565,2009,Pontiac,Torrent,Base,SUV,Automatic,2ckdl33f096201887,49450,Tdaf Remarketing,9475,10500,2015-06-30,Florida,6
9828,2009,Porsche,Cayenne,GTS,suv,Automatic,wp1ad29p49la60409,65234,Kapitolia Auto Llc,30200,30250,2015-06-19,Nevada,6
5886,2013,Ram,2500,Tradesman,Crew Cab,Automatic,3c6ur5hl6dg580964,92961,Enterprise Fleet Management Exchange,22500,23500,2015-07-02,Texas,2
14989,2011,Rolls-Royce,Ghost,Base,sedan,Automatic,sca664s55bux50201,15450,Financial Services Remarketing (Bmw Int),146000,150000,2015-06-04,California,4
33156,2005,Saab,9-2X,Linear,wagon,Automatic,jf4gg61655h056338,38275,Adk Auto Brokers Inc,2900,4000,2015-06-18,New York,10
12919,2008,Saturn,Outlook,XR,suv,Automatic,5gzev23758j168989,115033,Vegas Motorcars Inc,7500,8750,2015-06-19,Nevada,7
36308,2013,Scion,FR-S,Base,coupe,Manual,jf1znaa11d1724601,17484,D&A Fine Cars,18450,16800,2015-06-19,Florida,2
47583,2013,Subaru,XV Crosstrek,Premium,suv,Automatic,jf2gpacc7dh852375,27739,Td Auto Finance,18750,17800,2015-07-09,Texas,2
45640,2007,Suzuki,XL7,Luxury,suv,Automatic,2s3da517176111246,94880,Carworks Inc,4000,5500,2015-07-07,Georgia,8
21076,2013,Tesla,Model S,Base,Sedan,Automatic,5yjsa1cgxdfp19512,25797,Ferrari Of Orange County,59200,55500,2015-05-21,California,2
30029,2012,Toyota,4Runner,SR5,SUV,Automatic,jtebu5jr5c5094399,62296,Mike Albert Fleet Solutions,26500,25100,2015-07-09,Texas,3
9010,2014,Volkswagen,Jetta,SE PZEV,sedan,Automatic,3vwd17aj8em395058,34325,Enterprise Vehicle Exchange / Tra / Rental / T...,11400,7600,2015-07-09,Georgia,1
10651,2007,Volvo,XC90,3.2,suv,Automatic,yv4cy982971355864,95769,Unique Autos,5950,8500,2015-07-09,Nevada,8
15531,2012,smart,fortwo,passion coupe,hatchback,Automatic,wmeej3ba7ck571862,13702,Mercedes-Benz Financial Services,6175,6000,2015-06-18,California,3

### Return vehicles sold in the last 90 days of the entire dataset timeline

In [14]:
# Ensure Sale Date is datetime
df['Sale Date'] = pd.to_datetime(df['Sale Date'])

# Maximum sale date
max_sale_date = df['Sale Date'].max()

# Filter rows where difference is >= 90 days
resu = df.loc[(max_sale_date - df['Sale Date']).dt.days >= 90]

resu

,Year,Make,Model,Trim,Body,Transmission,Vehicle Identification Number,Odometer,Seller,Market Price,Selling Price,Sale Date,State,Age
0,2004,Ford,Explorer,Limited,SUV,Automatic,1fmzu65k54ua59709,171116,Barnett Finance Company,2500,1700,2015-02-17,Georgia,11
2,2014,Dodge,Grand Caravan,SXT,Minivan,Automatic,2c4rdgcg2er173190,37928,Avis Corporation,16200,16200,2015-02-12,South Carolina,1
4,2011,Hyundai,Elantra,GLS PZEV,Sedan,Automatic,5npdh4aexbh018071,69185,Wholesale Inc # 2,9575,10300,2015-01-21,Tennessee,4
5,2012,Nissan,Leaf,SL,Hatchback,Automatic,jn1az0cp2ct018461,23801,Nissan Motor Acceptance Corporation,10600,11100,2015-02-25,California,3
6,2010,Dodge,Avenger,SXT,Sedan,Automatic,1b3cc4fb2an189535,110704,Exeter Finance Corp,5100,5600,2015-02-10,Tennessee,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2013,Nissan,Altima,2.5,Sedan,Automatic,1n4al3ap5dn468314,32702,Nissan-Infiniti Lt,13800,13000,2015-02-26,Illinois,2
49996,2005,Mercedes-Benz,E-Class,E320,Sedan,Automatic,wdbuf65j95a624447,123165,Westlake Financial Services,6075,4100,2015-01-08,Florida,10
49997,2013,Dodge,Dart,SXT,Sedan,Automatic,1c3cdfba9dd143722,47130,Wells Fargo Dealer Services,11400,11000,2015-03-04,Texas,2
49998,2008,Toyota,RAV4,Limited,SUV,Automatic,jtmzd31vx85115663,102712,Infinity Auto Sales Llc,9525,8600,2015-03-05,Virginia,7
49999,2013,Chevrolet,Camaro,SS,Convertible,Automatic,2g1fk3dj8d9138852,53105,Tdaf Remarketing,21400,23400,2015-02-17,Florida,2

### List transactions where Selling Price exceeds the 90th percentile of all selling prices.

In [15]:
# Calculate the 90th percentile of Selling Price
price_90 = df['Selling Price'].quantile(0.9)

# Filter rows where Selling Price exceeds the 90th percentile
high_price_sales = df.loc[df['Selling Price'] > price_90]

high_price_sales

,Year,Make,Model,Trim,Body,Transmission,Vehicle Identification Number,Odometer,Seller,Market Price,Selling Price,Sale Date,State,Age
17,2014,Buick,Enclave,Premium Group,SUV,Automatic,5gakvckd9ej225953,25352,Gm Remarketing,35200,33700,2015-02-19,Illinois,1
32,2014,Ford,Explorer,Limited,SUV,Automatic,1fm5k8f8xegb11760,36374,Ars/Avis Budget Group,25600,25400,2015-05-27,Minnesota,1
40,2014,GMC,Terrain,SLT-2,SUV,Automatic,2gkflye35e6271285,15841,Gm Remarketing,28100,25900,2015-03-05,Michigan,1
48,2011,Ford,F-250 Super Duty,Lariat,Crew Cab,Automatic,1ft7w2bt5bec62327,41563,Woodhouse Ford Inc,39500,39500,2015-02-05,Texas,4
57,2013,Audi,allroad,Premium Plus quattro,Wagon,Automatic,wa1ufafl8da062327,56262,Fratelli Investment Group,27600,27000,2015-02-12,California,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49956,2013,Lexus,RX 350,Base,SUV,Automatic,2t2bk1ba2dc176716,20345,Lexus Financial Services,34700,33500,2015-02-03,Ohio,2
49965,2012,Fisker,Karma,Eco-Sport,Sedan,Automatic,yh4k14aa4ca000463,18593,Innovative Auto Llc,48200,46500,2015-02-12,Georgia,3
49979,2015,Chevrolet,Suburban,LTZ,SUV,Automatic,1gnsckkc6fr206194,16293,Enterprise Veh Exchange/Rental,52200,51500,2015-02-20,Florida,0
49988,2014,BMW,3 Series,328d xDrive,sedan,Automatic,wba3d5c55ekx99045,3258,Bmw North America Raa,30400,30000,2015-06-16,Ohio,1
49991,2013,Lexus,GS 350,Base,sedan,Automatic,jthbe1bl2d5014108,26897,High Bid Trading Co Inc,30500,31500,2015-06-18,California,2

### Compute the average Selling Price and average Odometer for each State.

In [16]:
fin=df.groupby("State").agg({
    "Selling Price":"mean",
    "Odometer":"mean"
})
fin

                Selling Price       Odometer
State
Arizona          12608.962264   68283.826415
California       14944.455471   66328.488742
Colorado         15263.371601   54533.217523
Florida          14182.684945   62313.057951
Georgia          12799.398687   77195.061914
Hawaii           11950.735294   49179.875000
Illinois         15512.140170   43718.676668
Indiana          10506.220096   72863.760766
Louisiana        10579.406780   86152.485876
Maryland          7696.072797   99439.857280
Massachusetts     6946.200000  107881.896000
Michigan         14964.674327   60412.623112
Minnesota        13981.317757   59451.635514
Mississippi      11360.789474   83298.884211
Missouri         14734.617576   58060.864242
Nebraska         12604.745283   72760.667453
Nevada           15433.719572   60671.365132
New Jersey       13495.951567   60008.398046
New Mexico        3307.894737  128555.052632
New York         12847.747495   65002.553106
North Carolina    8840.382729  100776.402146
Ohio             14145.288238   63749.298931
Oklahoma          6978.571429  132019.142857
Oregon           11439.830508   61733.830508
Pennsylvania     14104.973149   57340.891830
Puerto Rico       9852.519380   55293.015504
South Carolina    9880.058081   88795.835859
Tennessee        16968.813259   49483.616903
Texas            13427.319322   71199.721130
Utah             12450.877193   92157.660819
Virginia          8527.886754   99884.278059
Washington       13849.903766   61981.589958
Wisconsin        14236.230539   63436.636727

### For each Make, calculate the total units sold (count of VIN) and the total revenue (sum of Selling Price).

In [17]:
total_Units_Sold=df.groupby("Make").size()
sum_of_selling_price=df.groupby("Make")["Selling Price"].sum()
new_selling_price_sum=pd.DataFrame(sum_of_selling_price)
new_units_sold=pd.DataFrame(total_Units_Sold)
new_selling_price_sum["total_Units_Sold"]=total_Units_Sold
new_selling_price_sum

               Selling Price  total_Units_Sold
Make
Acura                5890075               446
Aston Martin          306100                 6
Audi                10099175               476
BMW                 37973575              1824
Bentley               188500                 3
Buick                4961954               494
Cadillac             9449571               661
Chevrolet           67809188              5773
Chrysler            16845669              1595
Dodge               31904833              2896
FIAT                  860725                87
Fisker                 46500                 1
Ford               125259319              8518
GMC                 15859590               934
Geo                      850                 2
HUMMER               1357050                93
Honda               29614325              2713
Hyundai             21057828              1936
Infiniti            29826383              1466
Isuzu                  18600                13
Jaguar               2795800               131
Jeep                20441200              1389
Kia                 19981930              1696
Lamborghini           110000                 1
Land Rover           4736800               137
Lexus               21921000              1083
Lincoln              9350010               525
MINI                 3859425               314
Maserati              548750                13
Mazda                7475879               728
Mercedes-Benz       31515681              1427
Mercury               561150               133
Mitsubishi           3063750               387
Nissan              55813546              4687
Oldsmobile             37675                44
Plymouth               21000                 3
Pontiac              1653800               454
Porsche              4524550               111
Ram                  9937550               405
Rolls-Royce           150000                 1
Saab                  102450                38
Saturn                936675               268
Scion                1667700               165
Subaru               6724450               436
Suzuki                380825                97
Tesla                 195750                 3
Toyota              47736800              3852
Volkswagen          11138474              1165
Volvo                3561675               333
smart                 228200                37

In [18]:
make_summary = df.groupby("Make").agg(
    total_units_sold=("Vehicle Identification Number", "count"),
    total_revenue=("Selling Price", "sum")
).reset_index()

make_summary

             Make  total_units_sold  total_revenue
0           Acura               446        5890075
1    Aston Martin                 6         306100
2            Audi               476       10099175
3             BMW              1824       37973575
4         Bentley                 3         188500
5           Buick               494        4961954
6        Cadillac               661        9449571
7       Chevrolet              5773       67809188
8        Chrysler              1595       16845669
9           Dodge              2896       31904833
10           FIAT                87         860725
11         Fisker                 1          46500
12           Ford              8518      125259319
13            GMC               934       15859590
14            Geo                 2            850
15         HUMMER                93        1357050
16          Honda              2713       29614325
17        Hyundai              1936       21057828
18       Infiniti              1466       29826383
19          Isuzu                13          18600
20         Jaguar               131        2795800
21           Jeep              1389       20441200
22            Kia              1696       19981930
23    Lamborghini                 1         110000
24     Land Rover               137        4736800
25          Lexus              1083       21921000
26        Lincoln               525        9350010
27           MINI               314        3859425
28       Maserati                13         548750
29          Mazda               728        7475879
30  Mercedes-Benz              1427       31515681
31        Mercury               133         561150
32     Mitsubishi               387        3063750
33         Nissan              4687       55813546
34     Oldsmobile                44          37675
35       Plymouth                 3          21000
36        Pontiac               454        1653800
37        Porsche               111        4524550
38            Ram               405        9937550
39    Rolls-Royce                 1         150000
40           Saab                38         102450
41         Saturn               268         936675
42          Scion               165        1667700
43         Subaru               436        6724450
44         Suzuki                97         380825
45          Tesla                 3         195750
46         Toyota              3852       47736800
47     Volkswagen              1165       11138474
48          Volvo               333        3561675
49          smart                37         228200

### Compute Delta = Selling Price – Market Price and find the median Delta for each Body style.

In [19]:
df["Delta"]=df["Selling Price"]-df["Market Price"]

new_df=df.groupby("Make").agg(
    median_delta=("Delta","median")
)
new_df

               median_delta
Make
Acura                  50.0
Aston Martin        -1100.0
Audi                  -50.0
BMW                   -75.0
Bentley              4400.0
Buick                -125.0
Cadillac              -25.0
Chevrolet               0.0
Chrysler             -100.0
Dodge                 -50.0
FIAT                   50.0
Fisker              -1700.0
Ford                  -75.0
GMC                    12.5
Geo                  -250.0
HUMMER                175.0
Honda                  25.0
Hyundai                 0.0
Infiniti              -50.0
Isuzu                  75.0
Jaguar               -125.0
Jeep                  -50.0
Kia                     0.0
Lamborghini         -1000.0
Land Rover           -300.0
Lexus                   0.0
Lincoln               -50.0
MINI                  -50.0
Maserati               50.0
Mazda                  50.0
Mercedes-Benz        -200.0
Mercury              -150.0
Mitsubishi              0.0
Nissan                  0.0
Oldsmobile           -125.0
Plymouth             -250.0
Pontiac              -225.0
Porsche                50.0
Ram                   -50.0
Rolls-Royce          4000.0
Saab                 -137.5
Saturn               -112.5
Scion                   0.0
Subaru                -50.0
Suzuki                -25.0
Tesla               -3700.0
Toyota                -50.0
Volkswagen            -25.0
Volvo                -100.0
smart                 -75.0

### For each State, calculate annual revenue (sum of Selling Price) and the year‑over‑year growth %

In [20]:
# annual_revenue=df.groupby("State").agg(
#     Annual_Revenue=("Selling Price","sum"),
# )
# annual_revenue["year_over_growth"]=df[]


# Ensure Sale Date is datetime
df['Sale Date'] = pd.to_datetime(df['Sale Date'])
df['Sale_Year'] = df['Sale Date'].dt.year

# Group by State and Year
annual_revenue = df.groupby(["State", "Sale_Year"]).agg(
    Annual_Revenue=("Selling Price", "sum")
).reset_index()




# Sort by State and Year
annual_revenue = annual_revenue.sort_values(["State", "Sale_Year"])

# Calculate year-over-year growth %
annual_revenue["YoY_Growth_%"] = annual_revenue.groupby("State")["Annual_Revenue"].pct_change() * 100

annual_revenue["YoY_Growth_%"]=annual_revenue["YoY_Growth_%"].fillna(0)
annual_revenue

         State  Sale_Year  Annual_Revenue  YoY_Growth_%
0      Arizona       2014         1125550      0.000000
1      Arizona       2015         8898575    690.597930
2   California       2014        12979350      0.000000
3   California       2015        91228338    602.872933
4     Colorado       2014          732700      0.000000
..         ...        ...             ...           ...
59    Virginia       2015         7611080    824.797084
60  Washington       2014          623150      0.000000
61  Washington       2015         9307231   1393.577951
62   Wisconsin       2014          758275      0.000000
63   Wisconsin       2015        13506428   1681.204444

[64 rows x 4 columns]

### Resample the data to a monthly frequency and compute the mean Selling Price for each month.

In [21]:

df=pd.read_csv(r"F:\KPIT\Pandas_All\Datasets\car_sales_usa_data 1.csv",parse_dates=["Sale Date"])
display(df.columns)
df=df.set_index("Sale Date")

ndf=df.resample("ME")["Selling Price"].agg("mean")
ndf

Index(['Year', 'Make', 'Model', 'Trim', 'Body', 'Transmission',
       'Vehicle Identification Number', 'Odometer', 'Seller', 'Market Price',
       'Selling Price', 'Sale Date', 'State'],
      dtype='object')

Sale Date
2014-01-31    12834.210526
2014-02-28             NaN
2014-03-31             NaN
2014-04-30             NaN
2014-05-31             NaN
2014-06-30             NaN
2014-07-31             NaN
2014-08-31             NaN
2014-09-30             NaN
2014-10-31             NaN
2014-11-30             NaN
2014-12-31    12600.545408
2015-01-31    13147.514126
2015-02-28    13635.189065
2015-03-31    13664.699366
2015-04-30    10419.893617
2015-05-31    13855.259815
2015-06-30    14519.394849
2015-07-31    16231.390909
Freq: ME, Name: Selling Price, dtype: float64

In [22]:
df.columns

Index(['Year', 'Make', 'Model', 'Trim', 'Body', 'Transmission',
       'Vehicle Identification Number', 'Odometer', 'Seller', 'Market Price',
       'Selling Price', 'State'],
      dtype='object')

### Resample to a weekly frequency (weeks ending on Sunday) and count the number of sales per week.

In [23]:
# new_df=df.resample("W")["Selling Price"].size()
# new_df=new_df.reset_index()
# new_df=new_df.rename(columns={"Selling Price":"Sale Count"})
# new_df["WeekDay"]=new_df["Sale Date"].dt.weekday
# new_df
df.columns
# Ensure datetime
# df["Sale Date"] = pd.to_datetime(df["Sale Date"])
# df = df.set_index("Sale Date")

# # Resample weekly (ending on Sunday) and count
# new_df = df.resample("W").size().to_frame(name="Weekly Sales")

# new_df

Index(['Year', 'Make', 'Model', 'Trim', 'Body', 'Transmission',
       'Vehicle Identification Number', 'Odometer', 'Seller', 'Market Price',
       'Selling Price', 'State'],
      dtype='object')

### Calculate a centered 6‑month rolling average of Odometer based on Sale Date.

In [24]:
monthly_odo=df.resample("ME")["Odometer"].mean()
roll_df=monthly_odo.rolling(window=6,center=True).mean()
roll_df=roll_df.to_frame(name="6 month rolling average")
roll_df

            6 month rolling average
Sale Date
2014-01-31                      NaN
2014-02-28                      NaN
2014-03-31                      NaN
2014-04-30                      NaN
2014-05-31                      NaN
2014-06-30                      NaN
2014-07-31                      NaN
2014-08-31                      NaN
2014-09-30                      NaN
2014-10-31                      NaN
2014-11-30                      NaN
2014-12-31                      NaN
2015-01-31                      NaN
2015-02-28                      NaN
2015-03-31             71051.742472
2015-04-30             69179.206134
2015-05-31             67072.588336
2015-06-30                      NaN
2015-07-31                      NaN

### For each month, extract the Selling Price of the first sale (minimum Sale Date within that month).

In [25]:
new_dff=df.resample("M").first()["Selling Price"]
new_dff

C:\Users\Pragyan Prakhar\AppData\Local\Temp\ipykernel_27480\963606937.py:1: FutureWarning:

'M' is deprecated and will be removed in a future version, please use 'ME' instead.

Sale Date
2014-01-31    10500.0
2014-02-28        NaN
2014-03-31        NaN
2014-04-30        NaN
2014-05-31        NaN
2014-06-30        NaN
2014-07-31        NaN
2014-08-31        NaN
2014-09-30        NaN
2014-10-31        NaN
2014-11-30        NaN
2014-12-31    20300.0
2015-01-31    11600.0
2015-02-28    17800.0
2015-03-31    11400.0
2015-04-30     4200.0
2015-05-31     2600.0
2015-06-30     7400.0
2015-07-31    13200.0
Freq: ME, Name: Selling Price, dtype: float64

### Generate a cumulative revenue series ordered by Sale Date.

In [64]:
ndres=df.resample("M")["Selling Price"].sum()
cumm_revenue=ndres.cumsum()
final_res=cumm_revenue.to_frame(name="Cummulative Revenue")
final_res=final_res.reset_index()
final_res["Month"]=final_res["Sale Date"].dt.to_period("M")
final_res=final_res.drop("Sale Date",axis=1)
final_res.set_index("Cummulative Revenue")
display(final_res)


bc=df.resample("ME")["Selling Price"].sum()
cumm=bc.cumsum()
cumm=pd.DataFrame(cumm)
cumm=cumm.reset_index()
cumm["Sale Date"]=cumm["Sale Date"].dt.to_period("M")
cumm=cumm.rename(columns={"Sale Date":"Month","Selling Price":"Cummulative Revenue"})
cumm=cumm[["Cummulative Revenue","Month"]]
display(cumm)

C:\Users\Pragyan Prakhar\AppData\Local\Temp\ipykernel_27480\3296484684.py:1: FutureWarning:

'M' is deprecated and will be removed in a future version, please use 'ME' instead.

    Cummulative Revenue    Month
0                243850  2014-01
1                243850  2014-02
2                243850  2014-03
3                243850  2014-04
4                243850  2014-05
5                243850  2014-06
6                243850  2014-07
7                243850  2014-08
8                243850  2014-09
9                243850  2014-10
10               243850  2014-11
11             49499382  2014-12
12            218891954  2015-01
13            421401782  2015-02
14            479627066  2015-03
15            481096271  2015-04
16            545675637  2015-05
17            678716852  2015-06
18            680502305  2015-07

    Cummulative Revenue    Month
0                243850  2014-01
1                243850  2014-02
2                243850  2014-03
3                243850  2014-04
4                243850  2014-05
5                243850  2014-06
6                243850  2014-07
7                243850  2014-08
8                243850  2014-09
9                243850  2014-10
10               243850  2014-11
11             49499382  2014-12
12            218891954  2015-01
13            421401782  2015-02
14            479627066  2015-03
15            481096271  2015-04
16            545675637  2015-05
17            678716852  2015-06
18            680502305  2015-07